USER = "user"
ACCOUNT = "account"
PROJECT = "project"
API_KEY = "api_key"
WORKSPACE = "workspace"
LOGIN_ACTIVITY = "login_activity"
WALLET_PHRASE = "wallet_phrase"
AUDIT_LOG = "audit_log"
FAVORITE_TAGS = "favorite_tags"
SECRET = "secrets"
USER_KEYS = "user_keys"
PROJECT_KEYS = "project_keys"
PASSWORD_HISTORY = "password_history"
PROJECT_ACTIVITY = "project_activity"

