version: '3'

vars:
  CONDA_ENV: "zecrypt-server"
  SERVER_DIR: "packages/backend-server"
  PORT: 8009

tasks:
  dev:
    desc: Start the FastAPI development server
    cmds:
      - |
        /opt/anaconda3/bin/conda run -n {{.CONDA_ENV}} bash -c "cd {{.SERVER_DIR}} && uvicorn app.main:app --reload --port {{.PORT}}"