name: Build and Push to DigitalOcean Container Registry

on:
  push:
    branches: [ main ]

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}  
  IMAGE_NAME: zec-backend
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DOCR
      run: doctl registry login

    - name: Build and push Docker image
      working-directory: ./packages/backend-server
      run: |
        BRANCH_NAME=${{ github.ref_name }}
        IMAGE_TAG=${BRANCH_NAME}-${GITHUB_SHA::7}
        
        # Build with branch-SHA tag
        docker build -t zec-backend:$IMAGE_TAG .
        docker tag zec-backend:$IMAGE_TAG registry.digitalocean.com/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${BRANCH_NAME}-latest
        docker push registry.digitalocean.com/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${BRANCH_NAME}-latest
