name: Build and Push to DigitalOcean Container Registry

on:
  push:
    branches: [ main ]

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DOCR
      run: doctl registry login

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./packages/backend-server 
        file: ./Dockerfile  
        push: true
        tags: |
          registry.digitalocean.com/${{ env.REGISTRY_NAME }}/zec-backend:latest
          registry.digitalocean.com/${{ env.REGISTRY_NAME }}/zec-backend:${{ github.sha }}
          registry.digitalocean.com/${{ env.REGISTRY_NAME }}/zec-backend:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    